### ISSUE TITLE
Rune etching with premine generate cenotaph

### ISSUE THREAD

**Issue by dcorral** [me-foundation/runestone-lib#75]
- Etching with the following batch.yaml 
```yaml
mode: separate-outputs

etching:
  rune: KVQRGSLPXYOAAAZZZAAASZA
  divisibility: 2
  premine: 1000
  supply: 10000.00
  symbol: $
  terms:
    amount: 100.00
    cap: 90
  turbo: false

inscriptions:
  - file: test1.png
    metadata:
      title: Delicious Mangos
      description: >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam semper,
        ligula ornare laoreet tincidunt, odio nisi euismod tortor, vel blandit
        metus est et odio. Nullam venenatis, urna et molestie vestibulum, orci
        mi efficitur risus, eu malesuada diam lorem sed velit. Nam fermentum
        dolor et luctus euismod.

```

- creates a Cenotaph 

```js
{
  flaws: [ 'unrecognized_even_tag' ],
  etching: 'KVQRGSLPXYOAAAZZZAAASZA'
}
```

- This rune is indexed by the ord server correctly and is not marked as cenotaph
- This PR might be of interest https://github.com/ordinals/ord/pull/3420 

- Proposed solution #74 

ord: `v0.18.5`
runestone-lib: `v1.0.2`
